# Pertemuan 6

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from array import array
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# define input sequence from airlinespassengers.csv
df = pd.read_csv('https://raw.githubusercontent.com/andreandriand/dataset/main/AirPassengers.csv')
series = df['#Passengers']
print(series.shape)
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(series, n_steps)
print(X.shape, y.shape)

# show each sample
for i in range(len(X)):
    print(X[i], y[i])

(144,)
(141, 3) (141,)
[112 118 132] 129
[118 132 129] 121
[132 129 121] 135
[129 121 135] 148
[121 135 148] 148
[135 148 148] 136
[148 148 136] 119
[148 136 119] 104
[136 119 104] 118
[119 104 118] 115
[104 118 115] 126
[118 115 126] 141
[115 126 141] 135
[126 141 135] 125
[141 135 125] 149
[135 125 149] 170
[125 149 170] 170
[149 170 170] 158
[170 170 158] 133
[170 158 133] 114
[158 133 114] 140
[133 114 140] 145
[114 140 145] 150
[140 145 150] 178
[145 150 178] 163
[150 178 163] 172
[178 163 172] 178
[163 172 178] 199
[172 178 199] 199
[178 199 199] 184
[199 199 184] 162
[199 184 162] 146
[184 162 146] 166
[162 146 166] 171
[146 166 171] 180
[166 171 180] 193
[171 180 193] 181
[180 193 181] 183
[193 181 183] 218
[181 183 218] 230
[183 218 230] 242
[218 230 242] 209
[230 242 209] 191
[242 209 191] 172
[209 191 172] 194
[191 172 194] 196
[172 194 196] 196
[194 196 196] 236
[196 196 236] 235
[196 236 235] 229
[236 235 229] 243
[235 229 243] 264
[229 243 264] 272
[243 264 272] 237
[264 272 237] 211
[272 237 211] 180
[237 211 180] 201
[211 180 201] 204
[180 201 204] 188
[201 204 188] 235
[204 188 235] 227
[188 235 227] 234
[235 227 234] 264
[227 234 264] 302
[234 264 302] 293
[264 302 293] 259
[302 293 259] 229
[293 259 229] 203
[259 229 203] 229
[229 203 229] 242
[203 229 242] 233
[229 242 233] 267
[242 233 267] 269
[233 267 269] 270
[267 269 270] 315
[269 270 315] 364
[270 315 364] 347
[315 364 347] 312
[364 347 312] 274
[347 312 274] 237
[312 274 237] 278
[274 237 278] 284
[237 278 284] 277
[278 284 277] 317
[284 277 317] 313
[277 317 313] 318
[317 313 318] 374
[313 318 374] 413
[318 374 413] 405
[374 413 405] 355
[413 405 355] 306
[405 355 306] 271
[355 306 271] 306
[306 271 306] 315
[271 306 315] 301
[306 315 301] 356
[315 301 356] 348
[301 356 348] 355
[356 348 355] 422
[348 355 422] 465
[355 422 465] 467
[422 465 467] 404
[465 467 404] 347
[467 404 347] 305
[404 347 305] 336
[347 305 336] 340
[305 336 340] 318
[336 340 318] 362
[340 318 362] 348
[318 362 348] 363
[362 348 363] 435
[348 363 435] 491
[363 435 491] 505
[435 491 505] 404
[491 505 404] 359
[505 404 359] 310
[404 359 310] 337
[359 310 337] 360
[310 337 360] 342
[337 360 342] 406
[360 342 406] 396
[342 406 396] 420
[406 396 420] 472
[396 420 472] 548
[420 472 548] 559
[472 548 559] 463
[548 559 463] 407
[559 463 407] 362
[463 407 362] 405
[407 362 405] 417
[362 405 417] 391
[405 417 391] 419
[417 391 419] 461
[391 419 461] 472
[419 461 472] 535
[461 472 535] 622
[472 535 622] 606
[535 622 606] 508
[622 606 508] 461
[606 508 461] 390
[508 461 390] 432

In [ ]:
newX = pd.DataFrame(X, columns=['Xt-2', 'Xt-1', 'Xt'])
newY = pd.DataFrame(y, columns=['Output'])

In [ ]:
newDf = pd.concat([newX,newY], axis=1)
newDf

     Xt-2  Xt-1   Xt  Output
0     112   118  132     129
1     118   132  129     121
2     132   129  121     135
3     129   121  135     148
4     121   135  148     148
..    ...   ...  ...     ...
136   472   535  622     606
137   535   622  606     508
138   622   606  508     461
139   606   508  461     390
140   508   461  390     432

[141 rows x 4 columns]

In [ ]:
csv = newDf.to_csv('timeseries.csv')